// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEDg5DZGllz6sEL3qEc4yMn_CNYrX9EQM',
    appId: '1:460707618255:web:da73f1ceefc3430db346ba',
    messagingSenderId: '460707618255',
    projectId: 'bloodwave-f77a8',
    authDomain: 'bloodwave-f77a8.firebaseapp.com',
    storageBucket: 'bloodwave-f77a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs4qL__yJCHtWqrgvjEaMxKmQYMTU9VeQ',
    appId: '1:460707618255:android:481fe75d18e9162bb346ba',
    messagingSenderId: '460707618255',
    projectId: 'bloodwave-f77a8',
    storageBucket: 'bloodwave-f77a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABStnFj1GaTy1wVFbvGfcHpLxQ-D4BkLk',
    appId: '1:460707618255:ios:de2be74e32f02855b346ba',
    messagingSenderId: '460707618255',
    projectId: 'bloodwave-f77a8',
    storageBucket: 'bloodwave-f77a8.appspot.com',
    iosClientId: '460707618255-gghvnuuaqd8qasbr7m6rqe6nv78qp6i7.apps.googleusercontent.com',
    iosBundleId: 'com.example.noell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABStnFj1GaTy1wVFbvGfcHpLxQ-D4BkLk',
    appId: '1:460707618255:ios:de2be74e32f02855b346ba',
    messagingSenderId: '460707618255',
    projectId: 'bloodwave-f77a8',
    storageBucket: 'bloodwave-f77a8.appspot.com',
    iosClientId: '460707618255-gghvnuuaqd8qasbr7m6rqe6nv78qp6i7.apps.googleusercontent.com',
    iosBundleId: 'com.example.noell',
  );
}
